ProjectPRN221/ProjectPRN221/Pages/Activity.cshtml.cs
using Data_Access.DTOs;
using Data_Access.Repository;
using Data_Access.Repository.Implement;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProjectPRN221.Helper;
namespace ProjectPRN221.Pages
{
	public class ActivityModel : PageModel
	{
		private readonly IAreaRepository areaRepository = new AreaRepository();
		private readonly ITimeSlotRepository timeSlotRepository = new TimeSlotRepository();
		private readonly ISessionRepository sessionRepository = new SessionRepository();
		private readonly IRoomRepository roomRepository = new RoomRepository();

		private IHttpContextAccessor httpContextAccessor;

		public ActivityModel(IHttpContextAccessor httpContextAccessor)
		{
			this.httpContextAccessor = httpContextAccessor;
		}

		public List<AreaDTO> Areas { get; set; }
		public List<TimeSlotDTO> TimeSlots { get; set; }
		public List<SessionDTO> CurrentSessions { get; set; }
		public List<RoomDTO> CurrentRooms { get; set; }

		public string Message { get; set; }

		[BindProperty]
		public string AreaId { get; set; }
		[BindProperty]
		public string DateView { get; set; }
		[BindProperty(SupportsGet = true)]
		public string LecturerId { get; set; }

		void GetData()
		{
			Areas = areaRepository.GetAllAreas();
			TimeSlots = timeSlotRepository.GetTimeSlots();
		}

		public void OnGet()
		{
			GetData();
		}

		public void OnPostSearch()
		{
			GetData();
			WebSessionHelper webSessionHelper = new WebSessionHelper(httpContextAccessor.HttpContext!.Session);
			webSessionHelper.SetCurrentLecturerId(LecturerId);
			CurrentSessions = sessionRepository.GetSessionsByLecturerId(LecturerId);
			webSessionHelper.SetSessionDTOs(CurrentSessions);
		}

		public void OnPostView()
		{
			GetData();
			CurrentRooms = roomRepository.GetRoomDTOsByAreaId(AreaId);
			WebSessionHelper webSessionHelper = new WebSessionHelper(httpContextAccessor.HttpContext!.Session);
			CurrentSessions = webSessionHelper.GetSessionDTOs();
			CurrentSessions = CurrentSessions.Where(cs => cs.Date == DateTime.Parse(DateView)).ToList();
			LecturerId = webSessionHelper.GetCurrentLecturerId();
		}
	}
}

ProjectPRN221/ProjectPRN221/Pages/ActivityAll.cshtml.cs
using Data_Access.DTOs;
using Data_Access.Repository;
using Data_Access.Repository.Implement;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProjectPRN221.Helper;
using System.Data;

namespace ProjectPRN221.Pages
{
	public class ActivityAllModel : PageModel
	{

		private IHttpContextAccessor httpContextAccessor;
		private readonly ITimeSlotRepository timeSlotRepository = new TimeSlotRepository();
		private readonly ISessionRepository sessionRepository = new SessionRepository();
		public List<TimeSlotDTO> TimeSlots { get; set; }
		[BindProperty]
		public string requireDate { get; set; }
		public List<DateTime> WeekDates { get; set; }
		[BindProperty(SupportsGet = true)]
		public string LecturerId { get; set; }
		public List<SessionDTO> CurrentSessions { get; set; }
		public string Message { get; set; }
		public ActivityAllModel(IHttpContextAccessor httpContextAccessor)
		{
			this.httpContextAccessor = httpContextAccessor;
			this.WeekDates = new List<DateTime>();
		}
		void GetData()
		{
			TimeSlots = timeSlotRepository.GetTimeSlots();
		}

		public void OnGet()
		{
			GetData();
		}

		public void OnPostSearch()
		{
			GetData();
			WebSessionHelper webSessionHelper = new WebSessionHelper(httpContextAccessor.HttpContext!.Session);
			webSessionHelper.SetCurrentLecturerId(LecturerId);
			CurrentSessions = sessionRepository.GetSessionsByLecturerId(LecturerId);
			webSessionHelper.SetSessionDTOs(CurrentSessions);
		}

		public void OnPostViewThisWeek()
		{
			GetData();
			WeekDates = DateTimeHelper.GetWeekDates(DateTime.Parse(requireDate));
			WebSessionHelper webSessionHelper = new WebSessionHelper(httpContextAccessor.HttpContext!.Session);
			CurrentSessions = webSessionHelper.GetSessionDTOs();
			CurrentSessions = CurrentSessions
				.Where(cs => cs.Date >= WeekDates.FirstOrDefault()
				&& cs.Date <= WeekDates.LastOrDefault())
				.ToList();
		}
	}
}

ProjectPRN221/ProjectPRN221/Pages/ChangeSchedule.cshtml.cs
using Data_Access.DTOs;
using Data_Access.Repository;
using Data_Access.Repository.Implement;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProjectPRN221.Helper;

namespace ProjectPRN221.Pages
{
	public class ChangeScheduleModel : PageModel
	{
		private IHttpContextAccessor httpContextAccessor;
		private readonly ISessionRepository sessionRepository = new SessionRepository();
		private readonly ITimeSlotRepository timeSlotRepository = new TimeSlotRepository();
		private readonly IRoomRepository roomRepository = new RoomRepository();
		public ChangeScheduleModel(IHttpContextAccessor httpContextAccessor)
		{
			this.httpContextAccessor = httpContextAccessor;
		}
		[BindProperty]
		public int SessionID { get; set; }
		public SessionDTO CurrentChangeSession { get; set; }
		public List<RoomDTO> AllRooms { get; set; }
		public List<TimeSlotDTO> TimeSlots { get; set; }

		[BindProperty(SupportsGet = true)]
		public string MappingDate { get; set; }
		[BindProperty]
		public int RoomId { get; set; }
		[BindProperty]
		public int TimeslotId { get; set; }
		[BindProperty]
		public string LecturerId { get; set; } = null!;
		public string Message { get; set; }
		void GetData()
		{
			TimeSlots = timeSlotRepository.GetTimeSlots();
			AllRooms = roomRepository.GetRoomDTOs();
		}

		public void OnGet(int SessionId)
		{
			GetData();
			SessionID = SessionId;
			CurrentChangeSession = sessionRepository.GetSession(SessionID);
			WebSessionHelper webSessionHelper = new WebSessionHelper(httpContextAccessor.HttpContext!.Session);
			webSessionHelper.SetCurrentSessionId(SessionID);
			TimeslotId = CurrentChangeSession.TimeslotId;
			RoomId = CurrentChangeSession.RoomId;
			LecturerId = CurrentChangeSession.LecturerId;
		}

		public void OnPostTestChange()
		{
			GetData();
			WebSessionHelper webSessionHelper = new WebSessionHelper(httpContextAccessor.HttpContext!.Session);
			SessionID = webSessionHelper.GetCurrentSessionId();
			CurrentChangeSession = sessionRepository.GetSession(SessionID);
			DateTime dateTime = DateTime.Parse(MappingDate);
			CurrentChangeSession.Date = dateTime;
			CurrentChangeSession.RoomId = RoomId;
			CurrentChangeSession.TimeslotId = TimeslotId;
			if (LecturerId != null)
				CurrentChangeSession.LecturerId = LecturerId;

			Message = sessionRepository.UpdateSession(CurrentChangeSession);
		}

		public void OnPostSaveChange()
		{

		}
	}
}

ProjectPRN221/ProjectPRN221/Pages/Index.cshtml.cs
using Data_Access.DAO;
using Data_Access.DTOs;
using Data_Access.Repository;
using Data_Access.Repository.Implement;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProjectPRN221.Helper;
using System.Text.Json;
using System.Xml.Serialization;

namespace ProjectPRN221.Pages
{
	public class IndexModel : PageModel
	{

		[BindProperty]
		public IFormFile FormFile { get; set; }
		public string Message { get; set; }
		public string Message2 { get; set; }
		public List<SessionDTORaw> filterSessionsRaw = new List<SessionDTORaw>();
		public List<SessionDTORaw> nonFilterSessionsRaw = new List<SessionDTORaw>();

		private readonly ISessionRepository sessionRepository = new SessionRepository();
		public void OnGet()
		{
			Message = string.Empty;
			Message2 = string.Empty;
		}

		public void OnPostImportSchedule()
		{
			var fileExtension = Path.GetExtension(FormFile.FileName).ToLower();
			Stream sr = FormFile.OpenReadStream();
			List<SessionDTORaw> originalSessionsRaw = new List<SessionDTORaw>();

			switch (fileExtension)
			{
				case ".json":
					originalSessionsRaw = JsonSerializer.Deserialize<List<SessionDTORaw>>(sr);
					ProcessImport(originalSessionsRaw);
					break;
				case ".csv":
					originalSessionsRaw = CsvFileHelper.CsvFileReader(sr);
					ProcessImport(originalSessionsRaw);
					break;
				case ".xml":
					XmlSerializer xmlSerializer = new XmlSerializer(typeof(List<SessionDTORaw>));
					ProcessImport(originalSessionsRaw);
					break;
				default:
					Message = "❌ Import Schedule: Fail. Cannot read data from file";
					break;
			}
		}

		void ProcessImport(List<SessionDTORaw> originalSessionsRaw)
		{
			filterSessionsRaw = SessionHelper.GetFinalFilteredSessions(originalSessionsRaw);
			nonFilterSessionsRaw = SessionHelper.GetNonFilteredSessions(originalSessionsRaw, filterSessionsRaw);

			foreach (var session in filterSessionsRaw)
			{
				var sessionsAfterConvert = SessionHelper.ConvertToSessionDTOCreates(session);
				foreach (var item in sessionsAfterConvert)
				{
					Message2 = "🔔 All schedules are new schedules";
					if (SessionDAO.Instance.IsExistingSession(item))
					{
						Message = "✅ Import Schedule Status: Done.";
						Message2 = "⚠️ Automatically skipped duplicate schedules";
					}
					else
					{
						sessionRepository.SaveSessionDTO(item);
						Message = "✅ Import Schedule Status: Done";
					}
				}
			}
		}
	}
}

ProjectPRN221/ProjectPRN221/Pages/Activity.cshtml
@page
@model ProjectPRN221.Pages.ActivityModel
@{
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<head>
	<link rel="stylesheet" href="~/assets/css/styles.css" />
	<link href="~/libs/bootstrap/css/bootstrap.css" rel="stylesheet" />
	<link href="~/libs/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
	<style>
		.table th,
		.table td {
			text-align: center; 
			vertical-align: middle !important; 
		}
	</style>
</head>
<body>
	<div class="container">
		<div class="row head-title">
			<div class="col-md-8">
				<h1>
					<span>FPT University Academic Portal</span>
				</h1>
			</div>
			<div class="col-md-4 mobile-app-ads">
				<div>
					<span><strong>FAP mobile app (myFAP) is ready at</strong></span>
				</div>
				<div style="display: flex; justify-content: space-between">
					<div>
						<a href="https://apps.apple.com/app/id1527723314">
							<img src="https://fap.fpt.edu.vn/images/app-store.png" style="width: 120px; height: 40px" alt="apple store" />
						</a>
					</div>
					<div>
						<a href="https://play.google.com/store/apps/details?id=com.fuct">
							<img src="https://fap.fpt.edu.vn/images/play-store.png" style="width: 120px; height: 40px" alt="google store" />
						</a>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<header class="header-bar">
					<div class="header-left">
						<span><a href="/">Home</a></span>&nbsp;|&nbsp;
						<span><a href="/Activity">Activity One Day</a></span>&nbsp;|&nbsp;
					</div>
					<div class="header-right">
						<span><a href="#">username</a></span>&nbsp;|&nbsp;
						<span><a href="#">logout</a></span>&nbsp;|&nbsp;
						<span><a href="#">CAMPUS: FPTU-Hòa Lạc</a></span>
					</div>
				</header>
			</div>
		</div>
		<div class="row" style="margin-top: 1em">
			<div class="col-md-12">
				<div style="display: flex; justify-content: center; align-self: center">
					<form method="post">
						Search:
						<input type="text" asp-for="LecturerId" name="LecturerId"/>
						<input type="submit" value="Search" asp-page-handler="Search" />
						<span>@Model.Message</span>
					</form>
				</div>
				<div class="activity-table">
					<table class="table table-bordered table-hover">
						<thead>
							<form method="post">
								<div class="center activity-search-bar">
									<div>
										CAMPUS:
										<select>
											<option>FU-HL</option>
											<option>FU-DA</option>
										</select>
										AREA:
										<select asp-for="AreaId" name="AreaId">
											<option value="-1">- All Areas -</option>
											@if (Model.Areas != null)
											{
												foreach (var item in Model.Areas)
												{
													<option value="@item.AreaId">@item.AreaName</option>
												}
											}
										</select>
										DATE:
										<input type="date" asp-for="DateView" name="DateView"/>
										<input type="submit" value="View" asp-page-handler="View" />
									</div>
								</div>
							</form>
						</thead>
						<tbody>
							<tr class="table-primary">
								<th>ROOM</th>
								@foreach (var ts in Model.TimeSlots)
								{
									<th>@ts.TimeslotName<br />( @ts.TimeslotDescription )</th>
								}
							</tr>
							@if (Model.CurrentRooms != null)
							{
								@foreach (var r in Model.CurrentRooms)
								{
									<tr>
										<td style="text-align: center">@r.AreaId - @r.RoomName</td>
										@foreach (var ts in Model.TimeSlots)
										{
											<td style="text-align: center">
												@foreach (var s in Model.CurrentSessions)
												{
													if (s.Timeslot.TimeslotId == ts.TimeslotId && s.RoomId == r.RoomId)
													{
														<a asp-page="/ChangeSchedule" asp-route-SessionId="@s.SessionId">@s.Group.GroupName</a><br />
														<a>@s.Group.Subject.SubjectId</a><br/>
														<a>@s.LecturerId</a>
													}
												}
											</td>
										}
									</tr>
								}
							}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</body>

ProjectPRN221/ProjectPRN221/Pages/ActivityAll.cshtml
@page
@model ProjectPRN221.Pages.ActivityAllModel
@{
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<head>
	<link rel="stylesheet" href="~/assets/css/styles.css" />
	<link href="~/libs/bootstrap/css/bootstrap.css" rel="stylesheet" />
	<link href="~/libs/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
	<link rel="stylesheet"
		  href="https://maxst.icons8.com/vue-static/landings/line-awesome/font-awesome-line-awesome/css/all.min.css">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
	<style>
		.table th,
		.table td {
			text-align: center;
			vertical-align: middle !important;
		}

		.thead th,
		.thead td {
			background-color: #6b90da;
		}
	</style>
</head>
<body>
	<div class="container">
		<div class="row head-title">
			<div class="col-md-8">
				<h1>
					<span>FPT University Academic Portal</span>
				</h1>
			</div>
			<div class="col-md-4 mobile-app-ads">
				<div>
					<span><strong>FAP mobile app (myFAP) is ready at</strong></span>
				</div>
				<div style="display: flex; justify-content: space-between">
					<div>
						<a href="https://apps.apple.com/app/id1527723314">
							<img src="https://fap.fpt.edu.vn/images/app-store.png" style="width: 120px; height: 40px" alt="apple store" />
						</a>
					</div>
					<div>
						<a href="https://play.google.com/store/apps/details?id=com.fuct">
							<img src="https://fap.fpt.edu.vn/images/play-store.png" style="width: 120px; height: 40px" alt="google store" />
						</a>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<header class="header-bar">
					<div class="header-left">
						<span><a href="/">Home</a></span>&nbsp;|&nbsp;
						<span><a href="/ActivityAll">Activity All Day</a></span>&nbsp;|&nbsp;
					</div>
					<div class="header-right">
						<span><a href="#">username</a></span>&nbsp;|&nbsp;
						<span><a href="#">logout</a></span>&nbsp;|&nbsp;
						<span><a href="#">CAMPUS: FPTU-Hòa Lạc</a></span>
					</div>
				</header>
			</div>
		</div>
		<div class="row" style="margin-top: 1em">
			<div class="col-md-12">
				<div style="display: flex; justify-content: center; align-self: center">
					<form method="post">
						Search:
						<input type="text" asp-for="LecturerId" name="LecturerId" />
						<input type="submit" value="Search" asp-page-handler="Search" />
						<span>@Model.Message</span>
					</form>
				</div>
				<div class="activity-table">
					<table class="table table-bordered table-hover">
						<thead class="thead">
							<tr>
								<th style="width: 15%">
									<form id="FormDate" method="post" style="margin: 0; padding: 0 !important" asp-page-handler="ViewThisWeek">
										<input type="date" asp-for="requireDate" name="requireDate" onchange="submitForm()" />
									</form>
								</th>
								<th>MON</th>
								<th>TUS</th>
								<th>WED</th>
								<th>THU</th>
								<th>FRI</th>
								<th>SAT</th>
								<th>SUN</th>
							</tr>
							<tr>
								@if (Model.WeekDates.Count != 0)
								{
									<td></td>
									@foreach (var d in Model.WeekDates)
									{
										<td>@d.Date.ToString("dd-MM-yyyy")</td>
									}
								}
							</tr>
						</thead>
						<tbody>
							@foreach (var ts in Model.TimeSlots)
							{
								<tr>
									<td>
										<b>@ts.TimeslotName</b> <br /> (@ts.TimeslotDescription)
									</td>
									@foreach (var d in Model.WeekDates)
									{
										<td style="text-align: center">
											@foreach (var cs in Model.CurrentSessions)
											{
												if (cs.TimeslotId == ts.TimeslotId && cs.Date == d)
												{
													<a asp-page="/ChangeSchedule" asp-route-SessionId="@cs.SessionId">@cs.Group.GroupName</a>
													<br />
													<a>@cs.Room.AreaId - @cs.Room.RoomName</a>
												}
											}
										</td>
									}
								</tr>
							}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
	<script>
		function submitForm() {
			document.getElementById("FormDate").submit();
		}
	</script>
</body>

ProjectPRN221/ProjectPRN221/Pages/ChangeSchedule.cshtml
@page
@model ProjectPRN221.Pages.ChangeScheduleModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<head>
	<link rel="stylesheet" href="~/assets/css/styles.css" />
	<link href="~/libs/bootstrap/css/bootstrap.css" rel="stylesheet" />
	<link href="~/libs/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
	<div class="container">
		<div class="row head-title">
			<div class="col-md-8">
				<h1>
					<span>FPT University Academic Portal</span>
				</h1>
			</div>
			<div class="col-md-4 mobile-app-ads">
				<div>
					<span><strong>FAP mobile app (myFAP) is ready at</strong></span>
				</div>
				<div style="display: flex; justify-content: space-between">
					<div>
						<a href="https://apps.apple.com/app/id1527723314">
							<img src="https://fap.fpt.edu.vn/images/app-store.png" style="width: 120px; height: 40px" alt="apple store" />
						</a>
					</div>
					<div>
						<a href="https://play.google.com/store/apps/details?id=com.fuct">
							<img src="https://fap.fpt.edu.vn/images/play-store.png" style="width: 120px; height: 40px" alt="google store" />
						</a>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<header class="header-bar">
					<div class="header-left">
						<span><a href="/">Home</a></span>&nbsp;|&nbsp;
						<span><a href="/ActivityAll">Activity All Day</a></span>&nbsp;|&nbsp;
						<span><a href="/Activity">Activity One Day</a></span>&nbsp;|&nbsp;
					</div>
					<div class="header-right">
						<span><a href="#">username</a></span>&nbsp;|&nbsp;
						<span><a href="#">logout</a></span>&nbsp;|&nbsp;
						<span><a href="#">CAMPUS: FPTU-Hòa Lạc</a></span>
					</div>
				</header>
			</div>
		</div>
		<div class="row" style="margin-top: 1em">
			<div class="col-md-12">
				<div>
					<h2>Change Schedule</h2>
				</div>
				<div class="change-schedule-table">
					<form method="post">
						@if (Model.Message != null)
						{
							if (Model.Message == "Session updated successfully.")
							{
								<p style="color: green">@Model.Message</p>
							}
							else
							{
								<p style="color: red">@Model.Message</p>
							}
						}
						<table>
							<tr>
								<td>New date</td>
								<td><input type="date" asp-for="MappingDate" value="@Model.CurrentChangeSession.Date.ToString("yyyy-MM-dd")" /></td>
							</tr>
							<tr>
								<td>New slot</td>
								<td>
									<select asp-for="TimeslotId">
										@foreach (var ts in @Model.TimeSlots)
										{
												<option value="@ts.TimeslotId">
													@ts.TimeslotName
												</option>
										}
									</select>
								</td>
							</tr>
							<tr>
								<td>New room</td>
								<td>
									<select asp-for="RoomId">
										@foreach (var r in @Model.AllRooms)
										{
												<option value="@r.RoomId">
													@r.AreaId - @r.RoomName
												</option>
										}
									</select>
								</td>
							</tr>
							<tr>
								<td>New teacher</td>
								<td><input type="text" asp-for="LecturerId" /></td>
							</tr>
							<tr>
								<td>SessionNo</td>
								<td>
									@Model.CurrentChangeSession.SessionNo
								</td>
							</tr>
							<tr>
								<td>Subject</td>
								<td>
									@Model.CurrentChangeSession.Group.SubjectId -
									@Model.CurrentChangeSession.Group.Subject.SubjectName
								</td>
							</tr>
							<tr>
								<td>Campus/Programme</td>
								<td>FU-HL</td>
							</tr>
							<tr>
								<td>Student group</td>
								<td>@Model.CurrentChangeSession.Group.GroupName</td>
							</tr>
							<tr>
								<td>Reason</td>
								<td>
									<textarea style="width: 100%">

											</textarea>
								</td>
							</tr>
							<tr>
								<td>Online</td>
								<td>
									@if (@Model.CurrentChangeSession.Online == true)
									{
										<input type="checkbox" checked />
									}
									else
									{
										<input type="checkbox" />
									}
								</td>
							</tr>
							<tr>
								<td></td>
								<td>
									<input type="submit" asp-page-handler="TestChange" value="Test Change" />
								</td>
							</tr>
							<tr>
								<td></td>
								<td>
									<input type="submit" asp-page-handler="Save Change" value="Save Change" />
								</td>
							</tr>
						</table>
					</form>
				</div>
			</div>
		</div>
	</div>
</body>